#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
#
# generated by wxGlade 0.9.3 on Tue Jul  2 14:48:00 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class configureFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: configureFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE | wx.FRAME_TOOL_WINDOW
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((200, 150))
        self.next_program = wx.Button(self, wx.ID_ANY, "Next program")
        self.chk_next_program = wx.CheckBox(self, wx.ID_ANY, "")
        self.volume_up = wx.Button(self, wx.ID_ANY, "Volume up")
        self.chk_volume_up = wx.CheckBox(self, wx.ID_ANY, "")
        self.volume_down = wx.Button(self, wx.ID_ANY, "Volume down")
        self.chk_volume_down = wx.CheckBox(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.next_program_define, self.next_program)
        self.Bind(wx.EVT_BUTTON, self.volume_up_define, self.volume_up)
        self.Bind(wx.EVT_BUTTON, self.volume_down_define, self.volume_down)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: configureFrame.__set_properties
        self.SetTitle("Configurer")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: configureFrame.__do_layout
        sizer_1 = wx.GridSizer(3, 2, 6, 6)
        sizer_1.Add(self.next_program, 0, wx.ALL | wx.EXPAND, 0)
        sizer_1.Add(self.chk_next_program, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(self.volume_up, 0, wx.EXPAND, 0)
        sizer_1.Add(self.chk_volume_up, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(self.volume_down, 0, wx.EXPAND, 0)
        sizer_1.Add(self.chk_volume_down, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def next_program_define(self, event):  # wxGlade: configureFrame.<event_handler>
        print("Event handler 'next_program_define' not implemented!")
        event.Skip()

    def volume_up_define(self, event):  # wxGlade: configureFrame.<event_handler>
        print("Event handler 'volume_up_define' not implemented!")
        event.Skip()

    def volume_down_define(self, event):  # wxGlade: configureFrame.<event_handler>
        print("Event handler 'volume_down_define' not implemented!")
        event.Skip()

# end of class configureFrame

class Configurer(wx.App):
    def OnInit(self):
        self.frame = configureFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class Configurer

if __name__ == "__main__":
    configurer_gui = Configurer(0)
    configurer_gui.MainLoop()
